name: Trigger Netlify build every hour

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          NETLIFY_BUILD_HOOK_URL: ${{ secrets.NETLIFY_BUILD_HOOK_URL }}
        run: curl -X POST -d {} $NETLIFY_BUILD_HOOK_URL
