name: Build and deploy hourly to Netlify

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 * * * *"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm run build
      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=_site
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}

